const CIH_NEWS_DATA = [
  {
    "id": 1,
    "title": "KẾT HỢP PHẪU THUẬT U TUYẾN GIÁP VÀ VIÊM TÚI MẬT MẠN ĐỒNG BỘ, GIÚP RÚT NGẮN THỜI GIAN ĐIỀU TRỊ VÀ HỒI PHỤC TỐT",
    "link": "https://cih.com.vn/phau-thuat-tuyen-giap-va-viem-tui-mat-man-dong-bo/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/SEO-SAN-5.webp",
    "date": "23/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": " Mới đây, Khoa Ngoại Tổng quát - Bệnh viện Quốc tế City đã điều trị thành công cho một khách hàng người Campuchia mắc đồng thời u lành tuyến...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 2,
    "title": "Thông báo chiêu sinh khóa Đào tạo liên tục (CME) – Hồi sinh tim phổi cơ bản – khóa 5",
    "link": "https://cih.com.vn/thong-bao-chieu-sinh-khoa-dao-tao-lien-tuc-cme-hoi-sinh-tim-phoi-co-ban-khoa-5/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/CME096.webp",
    "date": "22/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Hoạt động đào tạo cập nhật kiến thức y khoa liên tục không chỉ là nhiệm vụ chuyên môn mà còn là tiêu chí quan trọng trong đánh giá chất lượn...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 3,
    "title": "Thông báo chiêu sinh khóa Đào tạo liên tục (CME) – Chăm sóc người bệnh toàn diện &#8211; khóa 1",
    "link": "https://cih.com.vn/thong-bao-chieu-sinh-khoa-dao-tao-lien-tuc-cme-cham-soc-nguoi-benh-toan-dien-khoa-1/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/CME113.webp",
    "date": "22/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Hoạt động đào tạo cập nhật kiến thức y khoa liên tục không chỉ là nhiệm vụ chuyên môn mà còn là tiêu chí quan trọng trong đánh giá chất lượn...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 4,
    "title": "Thông báo chiêu sinh khóa Đào tạo liên tục (CME) – Tăng cường năng lực quản lý điều dưỡng &#8211; khóa 2",
    "link": "https://cih.com.vn/thong-bao-chieu-sinh-khoa-dao-tao-lien-tuc-cme-tang-cuong-nang-luc-quan-ly-dieu-duong-khoa-2/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/CME112.webp",
    "date": "22/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Hoạt động đào tạo cập nhật kiến thức y khoa liên tục không chỉ là nhiệm vụ chuyên môn mà còn là tiêu chí quan trọng trong đánh giá chất lượn...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 5,
    "title": "Thông báo chiêu sinh khóa Đào tạo liên tục (CME) – Phòng và kiểm soát nhiễm khuẩn &#8211; khóa 5",
    "link": "https://cih.com.vn/thong-bao-chieu-sinh-khoa-dao-tao-lien-tuc-cme-phong-va-kiem-soat-nhiem-khuan-khoa-5/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/CME111.webp",
    "date": "22/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Hoạt động đào tạo cập nhật kiến thức y khoa liên tục không chỉ là nhiệm vụ chuyên môn mà còn là tiêu chí quan trọng trong đánh giá chất lượn...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 6,
    "title": "ĐA CHẤN THƯƠNG DO TAI NẠN GIAO THÔNG: HÀNH TRÌNH GIÀNH LẠI SỰ SỐNG NHỜ ĐIỀU TRỊ ĐA CHUYÊN KHOA",
    "link": "https://cih.com.vn/da-chan-thuong-do-tai-nan-giao-thong/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/16-1024x576.webp",
    "date": "22/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Đa chấn thương do tai nạn giao thông có thể đe dọa tính mạng nếu không được cấp cứu kịp thời. Tìm hiểu ca bệnh hồi phục nhờ phối hợp đa chuy...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">Đa chấn thương do tai nạn giao thông nguy hiểm như thế nào?</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-2\"><span class=\"ftwp-text\">Đa chấn thương do tai nạn giao thông, ca bệnh tại Bệnh viện Quốc tế City</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-3\"><span class=\"ftwp-text\">Điều trị theo từng giai đoạn để kiểm soát tình trạng nguy kịch</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-4\"><span class=\"ftwp-text\">Người bệnh dần phục hồi các chức năng quan trọng</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-5\"><span class=\"ftwp-text\">Phối hợp đa chuyên khoa: Chìa khóa điều trị thành công đa chấn thương do tai nạn giao thông</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-6\"><span class=\"ftwp-text\">Khuyến cáo từ chuyên gia</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-7\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 7,
    "title": "KẾT NỐI SỨC MẠNH Y TẾ TƯ NHÂN PHÍA NAM: MADAM TRẦN THỊ LÂM GIỮ VAI TRÒ CHỦ TỊCH CHI HỘI",
    "link": "https://cih.com.vn/ket-noi-suc-manh-y-te-tu-nhan-phia-nam-madam-tran-thi-lam-giu-vai-tro-chu-tich-chi-hoi/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/1784637313294_7802592359529439111_7802592359529439111_3ff39bffa229aa52d9d3857daa11f902-1024x683.webp",
    "date": "21/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Ngày 20/07/2026, Hiệp hội Bệnh viện tư nhân Việt Nam đã chính thức tổ chức Diễn đàn hợp tác kết nối cộng đồng y tế tư nhân, đồng thời thống ...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 8,
    "title": "Lan tỏa tri thức – Truyền cảm hứng sống khỏe, sống đẹp",
    "link": "https://cih.com.vn/lan-toa-tri-thuc-truyen-cam-hung-song-khoe-song-dep/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/01bs.webp",
    "date": "20/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Vừa qua, tại Workshop &quot;Du lịch xanh &amp; Sức khỏe tinh thần&quot; do Trường Đại học Văn Hiến tổ chức, ThS.BS. Trần Quốc Thành – Giám đốc Điều hà...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 9,
    "title": "HỘI THẢO TẦM SOÁT UNG THƯ VÚ – PHÁT HIỆN SỚM, NÂNG CAO CƠ HỘI ĐIỀU TRỊ",
    "link": "https://cih.com.vn/hoi-thao-tam-soat-ung-thu-vu-phat-hien-som-nang-cao-co-hoi-dieu-tri/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/POST-TONG-3.webp",
    "date": "20/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "💗 Bạn có biết? Ung thư vú là một trong những bệnh ung thư phổ biến nhất ở phụ nữ. Tuy nhiên, nếu được phát hiện ở giai đoạn sớm, tỷ lệ điều ...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 10,
    "title": "SAU ĐUỐI NƯỚC CÓ CẦN NHẬP VIỆN KHÔNG? 3 BIẾN CHỨNG KHÔNG NÊN CHỦ QUAN",
    "link": "https://cih.com.vn/sau-duoi-nuoc-co-can-nhap-vien-khong/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/47-1024x576.webp",
    "date": "18/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Sau đuối nước có cần nhập viện không? Tìm hiểu các biến chứng nguy hiểm, dấu hiệu cần cấp cứu và khuyến cáo từ bác sĩ để xử trí kịp thời. Đu...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">Vì sao người bị đuối nước dù đã tỉnh vẫn cần đến bệnh viện?</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-2\"><span class=\"ftwp-text\">Những biến chứng có thể xảy ra sau đuối nước</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-3\"><span class=\"ftwp-text\">Các biến chứng khác cần lưu ý</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-4\"><span class=\"ftwp-text\">Những dấu hiệu cảnh báo cần đi cấp cứu ngay</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-5\"><span class=\"ftwp-text\">Người nhà nên làm gì sau khi đưa nạn nhân bị đuối nước lên bờ?</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-6\"><span class=\"ftwp-text\">Có nên tự theo dõi nạn nhân bị đuối nước tại nhà?</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-7\"><span class=\"ftwp-text\">Vai trò của Khoa Cấp cứu trong chăm sóc nạn nhân sau đuối nước</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-8\"><span class=\"ftwp-text\">Khuyến cáo từ bác sĩ</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-9\"><span class=\"ftwp-text\">Thông tin từ Bệnh viện Quốc tế City</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-10\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 11,
    "title": "Thông tin bảo hiểm",
    "link": "https://cih.com.vn/thong-tin-bao-hiem/",
    "img": "https://cih.com.vn/images/12.2023/Bo-him-lin-kt.jpg",
    "date": "01/11/2024",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Thông tin Bảo hiểm tại Bệnh viện Quốc tế City:",
    "content": "<p>Thông tin bảo hiểm</p>"
  },
  {
    "id": 12,
    "title": "10 năm chịu đựng đau đớn, bệnh nhân 76 tuổi tìm lại hạnh phúc sau ca thay khớp gối",
    "link": "https://cih.com.vn/10-nam-chiu-dung-dau-don-benh-nhan-76-tuoi-tim-lai-hanh-phuc-sau-ca-thay-khop-goi/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/1thumb.webp",
    "date": "17/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "“Mổ xong có đi lại được không?”, “Tuổi cao rồi, phẫu thuật có nguy hiểm không?” – đó là những băn khoăn phổ biến của nhiều người bệnh khi đư...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 13,
    "title": "BỆNH VIỆN QUỐC TẾ CITY ĐÓN BỆNH CẤP CỨU 0 ĐỒNG TRONG PHẠM VI 15KM",
    "link": "https://cih.com.vn/benh-vien-quoc-te-city-don-benh-cap-cuu-0-dong-trong-pham-vi-15km/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/ZALO-OA-1.webp",
    "date": "15/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Nhằm tạo điều kiện cấp cứu kịp thời cho bệnh nhân, từ nay đến hết ngày 31/12/2026, Bệnh viện Quốc tế City triển khai chương trình ‘Đón bệnh ...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 14,
    "title": "BỆNH VIỆN QUỐC TẾ CITY – CƠ SỞ ĐỦ ĐIỀU KIỆN ĐÀO TẠO CẬP NHẬT KIẾN THỨC Y KHOA LIÊN TỤC THEO QUY ĐỊNH BỘ Y TẾ (NGÀY CÔNG BỐ 13/07/2026)",
    "link": "https://cih.com.vn/benh-vien-quoc-te-city-co-so-du-dieu-kien-dao-tao-cap-nhat-kien-thuc-y-khoa-lien-tuc-theo-quy-dinh-bo-y-te-ngay-cong-bo-13-07-2026/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/AVATAR_CSPL_DAO-TAO-LIEN-TUC.webp",
    "date": "14/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Trong bối cảnh yêu cầu về cập nhật kiến thức y khoa liên tục (CME) ngày càng trở thành tiêu chuẩn bắt buộc đối với nhân viên y tế, việc lựa ...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 15,
    "title": "ỨNG DỤNG CÔNG NGHỆ BẢN ĐỒ TIM 3D ĐIỀU TRỊ RỐI LOẠN NHỊP TIM",
    "link": "https://cih.com.vn/dieu-tri-roi-loan-nhip-tim/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/huynh-cong-tuan.webp",
    "date": "13/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Tại Bệnh viện Quốc tế City (CIH), hệ thống thăm dò điện sinh lý và lập bản đồ tim 3D được sử dụng như một công cụ hỗ trợ bác sĩ phân tích cơ...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 16,
    "title": "Thông báo chiêu sinh khóa Đào tạo liên tục (CME) – Hồi sinh tim phổi cơ bản – khóa 4",
    "link": "https://cih.com.vn/thong-bao-chieu-sinh-khoa-dao-tao-lien-tuc-cme-hoi-sinh-tim-phoi-co-ban-khoa-4/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/CME095.webp",
    "date": "11/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Hoạt động đào tạo cập nhật kiến thức y khoa liên tục không chỉ là nhiệm vụ chuyên môn mà còn là tiêu chí quan trọng trong đánh giá chất lượn...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 17,
    "title": "CHUNG TAY XÂY DỰNG CỘNG ĐỒNG AN TOÀN, KHÔNG MA TÚY",
    "link": "https://cih.com.vn/chung-tay-xay-dung-cong-dong-an-toan-khong-ma-tuy/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/Ban-sao-cua-CTCH-Truoc-va-sau-PT-thay-khop-hang-2.webp",
    "date": "10/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Ma túy là một trong những hiểm họa nghiêm trọng đối với sức khỏe con người và sự phát triển bền vững của xã hội. Không chỉ gây nghiện và hủy...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 18,
    "title": "DANH SÁCH NGƯỜI THỰC HÀNH KHÁM BỆNH, CHỮA BỆNH TẠI BỆNH VIỆN QUỐC TẾ CITY NĂM 2026 (TÍNH ĐẾN NGÀY 06/07/2026)",
    "link": "https://cih.com.vn/danh-sach-nguoi-thuc-hanh-kham-benh-chua-benh-tai-benh-vien-quoc-te-city-nam-2026-tinh-den-ngay-06-07-2026/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/AVATAR_DS_NGUOI-THAM-GIA-KHOA-DTTH.webp",
    "date": "09/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Dưới đây là Danh sách người thực hành khám bệnh, chữa bệnh tại Bệnh viện Quốc tế City năm 2026 (tính đến ngày 08/06/2026). Thông tin chi tiế...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 19,
    "title": "Thông báo chiêu sinh khóa Đào tạo liên tục (CME) – Hồi sinh tim phổi cơ bản – khóa 3",
    "link": "https://cih.com.vn/thong-bao-chieu-sinh-khoa-dao-tao-lien-tuc-cme-hoi-sinh-tim-phoi-co-ban-khoa-3/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/CME094.webp",
    "date": "09/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Hoạt động đào tạo cập nhật kiến thức y khoa liên tục không chỉ là nhiệm vụ chuyên môn mà còn là tiêu chí quan trọng trong đánh giá chất lượn...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 20,
    "title": "BUỔI CHIA SẺ ĐẶC BIỆT THÁNG 7: “CÁC PHƯƠNG PHÁP CĂNG CHỈ THẨM MỸ” CÙNG GS. BS. KWON HAN JIN",
    "link": "https://cih.com.vn/buoi-chia-se-dac-biet-thang-7-cac-phuong-phap-cang-chi-tham-my-cung-gs-bs-kwon-han-jin/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/ZALO-OA.webp",
    "date": "08/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Trong tháng 7 này, Trung tâm Thẩm mỹ - Y học tái tạo, Bệnh viện Quốc tế City vinh hạnh chào đón GS. BS. Kwon Han Jin – Bậc thầy Thẩm mỹ đến ...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">Thông tin chương trình</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-2\"><span class=\"ftwp-text\">Phù hợp</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-3\"><span class=\"ftwp-text\">Đặc quyền VIP dành riêng cho Quý khách đăng ký tham gia</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-4\"><span class=\"ftwp-text\">Vì sao không thể bỏ lỡ buổi giao lưu chia sẻ với GS. BS. Kwon Han Jin?</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-5\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 21,
    "title": "THÔNG BÁO BỆNH VIỆN QUỐC TẾ CITY ĐÁP ỨNG YÊU CẦU LÀ CƠ SỞ THỰC HÀNH TRONG ĐÀO TẠO KHỐI NGÀNH SỨC KHỎE – LẦN 3 (CHUYÊN KHOA I: DƯỢC LÝ, DƯỢC LÂM SÀNG &#038; ĐẠI HỌC: DƯỢC SĨ)",
    "link": "https://cih.com.vn/thong-bao-benh-vien-quoc-te-city-dap-ung-yeu-cau-la-co-so-thuc-hanh-trong-dao-tao-khoi-nganh-suc-khoe-lan-3-chuyen-khoa-i-duoc-ly-duoc-lam-sang-dai-hoc-duoc-si/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/AVATAR_DAO-TAO-KHOI-NGANH-SUC-KHOE.webp",
    "date": "06/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Bệnh viện Quốc tế City trân trọng thông báo về việc đáp ứng đầy đủ các yêu cầu để trở thành cơ sở thực hành trong đào tạo khối ngành sức khỏ...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 22,
    "title": "KHU Y TẾ KỸ THUẬT CAO TP.HCM CHUNG TAY LAN TỎA GIÁ TRỊ CHĂM SÓC SỨC KHỎE CỘNG ĐỒNG",
    "link": "https://cih.com.vn/khu-y-te-ky-thuat-cao-tp-hcm-chung-tay-lan-toa-gia-tri-cham-soc-suc-khoe-cong-dong/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/1-1024x683.webp",
    "date": "04/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Ngày 03/07/2026 vừa qua, Ban lãnh đạo Khu Y tế Kỹ thuật cao TP.HCM tham dự sự kiện Kỷ niệm 01 năm phát hành sách &quot;Khỏe đẹp từ gốc&quot; và Ra mắt...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 23,
    "title": "CHÚC MỪNG VIỆN ĐÀO TẠO VÀ NGHIÊN CỨU KHOA HỌC &#8211; BỆNH VIỆN QUỐC TẾ CITY ĐƯỢC CÔNG BỐ LÀ CƠ SỞ THỰC HÀNH TRONG ĐÀO TẠO CHUYÊN NGÀNH DƯỢC SĨ HỆ ĐẠI HỌC VÀ CHUYÊN KHOA I",
    "link": "https://cih.com.vn/chuc-mung-vien-dao-tao-va-nghien-cuu-khoa-hoc-benh-vien-quoc-te-city-duoc-cong-bo-la-co-so-thuc-hanh-trong-dao-tao-chuyen-nganh-duoc-si-he-dai-hoc-va-chuyen-khoa-i/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/CONG-BO-CO-SO-THUC-HANH.webp",
    "date": "03/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Căn cứ theo Thông báo số 5310/TB-SYT ngày 02/07/2026 của Sở Y tế TP. Hồ Chí Minh, Bệnh viện Quốc tế City chính thức đáp ứng yêu cầu là cơ sở...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 24,
    "title": "Hội thảo Tim mạch – Đột quỵ 2026: Tầm soát sớm bệnh lý tim mạch và đột quỵ để bảo vệ sức khỏe toàn diện",
    "link": "https://cih.com.vn/hoi-thao-tam-soat-tim-mach-dot-quy-2026/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/COVER-FB-1024x664.webp",
    "date": "03/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Hội thảo Tim mạch – Đột quỵ 2026: Khám và tầm soát sớm bệnh lý tim mạch – đột quỵ cùng chuyên gia đầu ngành, nhận ưu đãi và quà tặng sức khỏ...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">Vì sao cần tầm soát sớm bệnh lý tim mạch và đột quỵ?</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-2\"><span class=\"ftwp-text\">Những ai nên tầm soát tim mạch và đột quỵ?</span></a></li><li class=\"ftwp-item ftwp-has-sub ftwp-collapse\"><button type=\"button\" aria-label=\"Expand or collapse\" class=\"ftwp-icon-collapse\"></button><a class=\"ftwp-anchor\" href=\"#ftoc-heading-3\"><span class=\"ftwp-text\">Hội thảo Tim mạch – Đột quỵ 2026: Cập nhật kiến thức, chủ động bảo vệ sức khỏe</span></a><ol class=\"ftwp-sub\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-4\"><span class=\"ftwp-text\">Thông tin hội thảo</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-5\"><span class=\"ftwp-text\">Đội ngũ diễn giả</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-6\"><span class=\"ftwp-text\">Thông qua những chia sẻ từ chuyên gia, khách tham dự sẽ được giải đáp các vấn đề được nhiều người quan tâm như:</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-7\"><span class=\"ftwp-text\">Quyền lợi đặc biệt dành cho khách tham dự</span></a></li></ol></li><li class=\"ftwp-item ftwp-has-sub ftwp-collapse\"><button type=\"button\" aria-label=\"Expand or collapse\" class=\"ftwp-icon-collapse\"></button><a class=\"ftwp-anchor\" href=\"#ftoc-heading-8\"><span class=\"ftwp-text\">Chủ động tầm soát hôm nay để bảo vệ sức khỏe ngày mai</span></a><ol class=\"ftwp-sub\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-9\"><span class=\"ftwp-text\">Đăng ký tham dự ngay hôm nay</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-10\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></li></ol></nav>"
  },
  {
    "id": 25,
    "title": "VIỆN ĐÀO TẠO &#038; NGHIÊN CỨU KHOA HỌC, BỆNH VIỆN QUỐC TẾ CITY TỔ CHỨC KHÓA ĐÀO TẠO CME &#8220;HỒI SINH TIM PHỔI CƠ BẢN&#8221; THÀNH CÔNG TỐT ĐẸP",
    "link": "https://cih.com.vn/vien-dao-tao-nghien-cuu-khoa-hoc-benh-vien-quoc-te-city-to-chuc-khoa-dao-tao-cme-hoi-sinh-tim-phoi-co-ban-thanh-cong-tot-dep/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/z7992453973706_208b221b7cf0ae1de2963c0882e97700-1024x683.webp",
    "date": "01/07/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Vừa qua ngày 30/06/2026, tại Hội trường Lotus, Viện Đào tạo &amp; Nghiên cứu khoa học, Bệnh viện Quốc tế City đã tổ chức thành công Khóa 2, ...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 26,
    "title": "Khu Y tế kỹ thuật cao TP.HCM mở rộng hợp tác y tế quốc tế với New Zealand, thúc đẩy phát triển du lịch y tế",
    "link": "https://cih.com.vn/khu-y-te-ky-thuat-cao-tp-hcm-mo-rong-hop-tac-y-te-quoc-te-voi-new-zealand-thuc-day-phat-trien-du-lich-y-te/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/07/03cih.webp",
    "date": "29/06/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Ngày 29/6/2026, tại Khu Y tế kỹ thuật cao TP.HCM (thuộc Tập đoàn Hoa Lâm), Bệnh viện Quốc tế City (CIH) và Bệnh viện Gia An 115 đã ký kết hợ...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 27,
    "title": "DẤU ẤN HỘI THẢO THẨM MỸ &#8220;NÂNG CẤP PHIÊN BẢN RẠNG RỠ SAU SINH&#8221;",
    "link": "https://cih.com.vn/dau-an-hoi-thao-tham-my-nang-cap-phien-ban-rang-ro-sau-sinh/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/06/23-1024x695.webp",
    "date": "27/06/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Sáng nay ngày 27/06/2026, Trung tâm Thẩm mỹ - Y học tái tạo, Bệnh viện Quốc tế City đã tổ chức thành công Hội thảo Thẩm mỹ với chủ đề “Nâng ...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 28,
    "title": "KHAI MẠC CHƯƠNG TRÌNH KIỂM TRA 83 TIÊU CHÍ, TỰ KIỂM TRA ĐÁNH GIÁ CHẤT LƯỢNG TẠI BỆNH VIỆN QUỐC TẾ CITY VÀ BỆNH VIỆN GIA AN 115",
    "link": "https://cih.com.vn/khai-mac-chuong-trinh-kiem-tra-83-tieu-chi/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/06/gen-h-z7970607012784_da8e51a562d54b49df86b2b3a4ce400a-1024x683.webp",
    "date": "24/06/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Sáng ngày 24/06/2026 tại Hội trường Diamond, Bệnh viện Quốc tế City và Bệnh viện Gia An 115 đã chính thức khai mạc Chương trình Tự kiểm tra ...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 29,
    "title": "Thay khớp háng thành công cho cụ bà 95 tuổi nhờ phối hợp đồng bộ đa chuyên khoa",
    "link": "https://cih.com.vn/thay-khop-hang-thanh-cong-cho-cu-ba-95-tuoi-nho-phoi-hop-dong-bo-da-chuyen-khoa/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/06/02-ctch01.webp",
    "date": "24/06/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Vừa qua, Khoa Chấn thương Chỉnh hình Bệnh viện Quốc tế City đã điều trị thành công một trường hợp chấn thương nặng ở người cao tuổi khi thực...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 30,
    "title": "DANH SÁCH NGƯỜI THỰC HÀNH KHÁM BỆNH, CHỮA BỆNH TẠI BỆNH VIỆN QUỐC TẾ CITY NĂM 2026 (TÍNH ĐẾN NGÀY 22/06/2026)",
    "link": "https://cih.com.vn/danh-sach-nguoi-thuc-hanh-kham-benh-chua-benh-tai-benh-vien-quoc-te-city-nam-2026-tinh-den-ngay-22-06-2026/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/06/AVATAR_DS_NGUOI-HOAN-THANH-KHOA-DTTH.webp",
    "date": "24/06/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Dưới đây là Danh sách người thực hành khám bệnh, chữa bệnh tại Bệnh viện Quốc tế City năm 2026 (tính đến ngày 22/06/2026). Thông tin chi tiế...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 31,
    "title": "Thông báo chiêu sinh khóa Đào tạo liên tục (CME) &#8211; Truyền thông giáo dục sức khỏe cơ bản – khóa 3",
    "link": "https://cih.com.vn/thong-bao-chieu-sinh-khoa-dao-tao-lien-tuc-cme-truyen-thong-giao-duc-suc-khoe-co-ban-khoa-3/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/06/Thong-bao-chieu-sinh-CME104-AVA.webp",
    "date": "24/06/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Hoạt động đào tạo cập nhật kiến thức y khoa liên tục không chỉ là nhiệm vụ chuyên môn mà còn là tiêu chí quan trọng trong đánh giá chất lượn...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 32,
    "title": "Thông báo chiêu sinh khóa Đào tạo liên tục (CME) &#8211; An toàn người bệnh – khóa 3",
    "link": "https://cih.com.vn/thong-bao-chieu-sinh-khoa-dao-tao-lien-tuc-cme-an-toan-nguoi-benh-khoa-3/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/06/Thong-bao-chieu-sinh-CME103-AVA.webp",
    "date": "24/06/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Hoạt động đào tạo cập nhật kiến thức y khoa liên tục không chỉ là nhiệm vụ chuyên môn mà còn là tiêu chí quan trọng trong đánh giá chất lượn...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 33,
    "title": "BIẾN CHỨNG ZONA: NAM DU KHÁCH CANADA 23 TUỔI NHẬP VIỆN SAU GẦN 48 GIỜ KHỞI PHÁT",
    "link": "https://cih.com.vn/bien-chung-zona/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/06/2560x1441_anh-bai-web-1024x576.webp",
    "date": "23/06/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Nam du khách Canada 23 tuổi, không bệnh nền, nhập viện sau gần 48 giờ khi biến chứng Zona tiến triển thành viêm mô tế bào diện rộng kèm viêm...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">Bệnh Zona khởi phát từ những dấu hiệu ban đầu như thế nào?</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-2\"><span class=\"ftwp-text\">Biến chứng Zona tiến triển chỉ sau gần 48 giờ</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-3\"><span class=\"ftwp-text\">Biến chứng Zona gây viêm mô tế bào và viêm mạch bạch huyết</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-4\"><span class=\"ftwp-text\">Điều trị kịp thời giúp kiểm soát biến chứng Zona</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-5\"><span class=\"ftwp-text\">Biến chứng Zona có nguy hiểm không?</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-6\"><span class=\"ftwp-text\">Dấu hiệu cảnh báo biến chứng Zona cần tái khám ngay</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-7\"><span class=\"ftwp-text\">Thông điệp từ ca bệnh: “Đừng chủ quan với Zona, không chỉ là những cơn đau”</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-8\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 34,
    "title": "CHAMPIONS LEAGUE 2026 – KẾT NỐI TINH THẦN, BỨT PHÁ GIỚI HẠN",
    "link": "https://cih.com.vn/champions-league-2026/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/06/z7963775668108_95574c1879a6c5293a4004cbdef162ca-1024x683.webp",
    "date": "22/06/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Giải bóng đá Champions League 2026 lan tỏa tinh thần đoàn kết trong hệ sinh thái Hoa Lâm Ngày 20/06/2026, Giải bóng đá nam Champions League ...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">Giải bóng đá Champions League 2026 lan tỏa tinh thần đoàn kết trong hệ sinh thái Hoa Lâm</span></a></li><li class=\"ftwp-item ftwp-has-sub ftwp-collapse\"><button type=\"button\" aria-label=\"Expand or collapse\" class=\"ftwp-icon-collapse\"></button><a class=\"ftwp-anchor\" href=\"#ftoc-heading-2\"><span class=\"ftwp-text\">Hoạt động thể thao ý nghĩa trong môi trường y tế và doanh nghiệp</span></a><ol class=\"ftwp-sub\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-3\"><span class=\"ftwp-text\">Quy tụ nhiều đơn vị trong hệ sinh thái Hoa Lâm và các đối tác đồng hành</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-4\"><span class=\"ftwp-text\">Những trận cầu hấp dẫn và tinh thần thi đấu chuyên nghiệp</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-5\"><span class=\"ftwp-text\">Lan tỏa văn hóa gắn kết và giá trị cộng đồng</span></a></li></ol></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-6\"><span class=\"ftwp-text\">Champions League 2026 – Biểu tượng của tinh thần đồng đội và khát vọng phát triển</span></a></li><li class=\"ftwp-item ftwp-has-sub ftwp-collapse\"><button type=\"button\" aria-label=\"Expand or collapse\" class=\"ftwp-icon-collapse\"></button><a class=\"ftwp-anchor\" href=\"#ftoc-heading-7\"><span class=\"ftwp-text\">Khép lại mùa giải đáng nhớ, mở ra những hành trình mới</span></a><ol class=\"ftwp-sub\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-8\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></li></ol></nav>"
  },
  {
    "id": 35,
    "title": "LỚP HỌC TIỀN SẢN QUY MÔ LỚN THÁNG 07: THEO DÕI THAI KỲ PHÁT TRIỂN VÀ NHẬN BIẾT DẤU HIỆU CHUYỂN DẠ",
    "link": "https://cih.com.vn/lop-hoc-tien-san-quy-mo-lon-thang-07-theo-doi-thai-ky-khoe-manh-nhan-biet-dau-hieu-chuyen-da/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/06/BANNER-WEB-2-1.webp",
    "date": "22/06/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Nhằm đồng hành cùng mẹ bầu trong giai đoạn cuối thai kỳ, giúp ba mẹ chuẩn bị tốt nhất cho ngày đón thiên thần nhỏ chào đời, Bệnh viện Quốc t...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 36,
    "title": "DANH SÁCH NGƯỜI THỰC HÀNH KHÁM BỆNH, CHỮA BỆNH TẠI BỆNH VIỆN QUỐC TẾ CITY NĂM 2026 (TÍNH ĐẾN NGÀY 08/06/2026)",
    "link": "https://cih.com.vn/danh-sach-nguoi-thuc-hanh-kham-benh-chua-benh-tai-benh-vien-quoc-te-city-nam-2026-tinh-den-ngay-08-06-2026/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/06/AVATAR_DS_NGUOI-THAM-GIA-KHOA-DTTH.webp",
    "date": "11/06/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Dưới đây là Danh sách người thực hành khám bệnh, chữa bệnh tại Bệnh viện Quốc tế City năm 2026 (tính đến ngày 08/06/2026). Thông tin chi tiế...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 37,
    "title": "HỘI THẢO THẨM MỸ THÁNG 6: NÂNG CẤP PHIÊN BẢN RẠNG RỠ SAU SINH",
    "link": "https://cih.com.vn/hoi-thao-tham-my-thang-6-nang-cap-phien-ban-rang-ro-sau-sinh/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/06/BANNER-WEB-3.webp",
    "date": "10/06/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Với mong muốn đồng hành cùng phái đẹp trên hành trình tìm lại vẻ đẹp và sự tự tin sau sinh cũng như trong cuộc sống, Trung tâm Thẩm mỹ – Y h...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">Thông tin chương trình</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-2\"><span class=\"ftwp-text\">Đối tượng nên tham dự hội thảo</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-3\"><span class=\"ftwp-text\">QUÝ KHÁCH HÀNG SẼ NHẬN ĐƯỢC GÌ TẠI HỘI THẢO?</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-4\"><span class=\"ftwp-text\">ƯU ĐÃI ĐẶC BIỆT TẠI HỘI THẢO</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-5\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 38,
    "title": "BỆNH VIỆN QUỐC TẾ CITY ĐÓN TIẾP ĐOÀN BMS JAPAN ĐẾN THAM QUAN VÀ LÀM VIỆC",
    "link": "https://cih.com.vn/benh-vien-quoc-te-city-don-tiep-doan-bms-japan-den-tham-quan-va-lam-viec/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/06/z7917494357002_7cf835b87626c9c1c39eb4c8fd757b84-1024x677.webp",
    "date": "10/06/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Sáng ngày 09/06/2026, Bệnh viện Quốc tế City đã đón tiếp đoàn công tác BMS Japan đến tham quan và làm việc tại Khu Y tế Kỹ thuật cao TP.HCM....",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 39,
    "title": "CẬP NHẬT DANH SÁCH NGƯỜI HOÀN THÀNH KHÓA THỰC HÀNH KHÁM BỆNH, CHỮA BỆNH TẠI BỆNH VIỆN QUỐC TẾ CITY NĂM 2026 (TÍNH ĐẾN NGÀY 01/06/2026)",
    "link": "https://cih.com.vn/cap-nhat-danh-sach-nguoi-hoan-thanh-khoa-thuc-hanh-kham-benh-chua-benh-tai-benh-vien-quoc-te-city-nam-2026-tinh-den-ngay-01-06-2026/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/05/AVATAR_DS_NGUOI-HOAN-THANH-KHOA-DTTH.webp",
    "date": "10/06/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Dưới đây là Danh sách người đã hoàn thành khóa thực hành khám bệnh, chữa bệnh tại Bệnh viện Quốc tế City năm 2026 (tính đến ngày 01/06/2026)...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 40,
    "title": "GIẢM 50% PHÍ KHÁM CHUYÊN KHOA – TRI ÂN KHÁCH HÀNG THÂN THIẾT",
    "link": "https://cih.com.vn/giam-50-phi-kham-chuyen-khoa/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/06/TONG-QUAN-CTRINH-1-1024x853.webp",
    "date": "06/06/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Bệnh viện Quốc tế City triển khai chương trình tri ân khách hàng thân thiết với ưu đãi giảm 50% phí khám chuyên khoa và giảm 50% chi phí Siê...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item ftwp-has-sub ftwp-collapse\"><button type=\"button\" aria-label=\"Expand or collapse\" class=\"ftwp-icon-collapse\"></button><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\"> GIẢM 50% PHÍ KHÁM CHUYÊN KHOA – TRI ÂN KHÁCH HÀNG THÂN THIẾT</span></a><ol class=\"ftwp-sub\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-2\"><span class=\"ftwp-text\">Cơ hội chăm sóc sức khỏe với chi phí tiết kiệm hơn</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-3\"><span class=\"ftwp-text\">Ưu đãi dành riêng cho khách hàng thân thiết</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-4\"><span class=\"ftwp-text\">Đối tượng và thời gian áp dụng</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-5\"><span class=\"ftwp-text\">Các chuyên khoa áp dụng ưu đãi</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-6\"><span class=\"ftwp-text\">Vì sao nhiều khách hàng tin tưởng lựa chọn Bệnh viện Quốc tế City?</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-7\"><span class=\"ftwp-text\">Đăng ký nhận ưu đãi ngay hôm nay</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-8\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></li></ol></nav>"
  },
  {
    "id": 41,
    "title": "Bệnh viện Quốc tế City “Top 3 Thương hiệu tiêu biểu Châu Á Thái Bình Dương 2026”",
    "link": "https://cih.com.vn/benh-vien-quoc-te-city-vinh-du-dat-top-3-thuong-hieu-tieu-bieu-chau-a-thai-binh-duong-2026/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/06/IMG_8701.webp",
    "date": "04/06/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Ngày 01/6/2026, tại thủ đô Bắc Kinh, Trung Quốc, Bệnh viện Quốc tế City thuộc Khu Y tế Kỹ thuật cao TPHCM vinh dự được xướng tên trong hạng ...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 42,
    "title": "ƯU ĐÃI KHÁCH MỚI: KHÁM CHUYÊN KHOA MIỄN PHÍ 100% – TẶNG THÊM 50% SIÊU ÂM HOẶC CHỤP X-QUANG",
    "link": "https://cih.com.vn/uu-dai-khach-moi-kham-chuyen-khoa-mien-phi/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/06/BANNER-WEB.webp",
    "date": "03/06/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Quý khách hàng đã quá mệt mỏi với tình trạng nghẹt mũi kéo dài, đau nhức răng, đau cổ vai gáy hay các vấn đề nội tiết? Đừng trì hoãn thăm kh...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">ĐẶC QUYỀN TẶNG RIÊNG CHO KHÁCH HÀNG MỚI</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-2\"><span class=\"ftwp-text\">ÁP DỤNG QUÝ KHÁCH MUỐN KHÁM CÁC CHUYÊN KHOA</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-3\"><span class=\"ftwp-text\">NHẬN THÊM ƯU ĐÃI 50% SIÊU ÂM HOẶC CHỤP X-QUANG</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-4\"><span class=\"ftwp-text\">THĂM KHÁM CÙNG ĐỘI NGŨ BÁC SĨ GIÀU KINH NGHIỆM</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-5\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 43,
    "title": "Thông báo chiêu sinh khóa Đào tạo liên tục (CME) &#8211; Hồi sinh tim phổi cơ bản – khóa 2",
    "link": "https://cih.com.vn/thong-bao-chieu-sinh-khoa-dao-tao-lien-tuc-cme-hoi-sinh-tim-phoi-co-ban-khoa-2/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/06/CME_HSTPCB_K2.webp",
    "date": "02/06/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Hoạt động đào tạo cập nhật kiến thức y khoa liên tục không chỉ là nhiệm vụ chuyên môn mà còn là tiêu chí quan trọng trong đánh giá chất lượn...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 44,
    "title": "DANH SÁCH NGƯỜI THỰC HÀNH KHÁM BỆNH, CHỮA BỆNH TẠI BỆNH VIỆN QUỐC TẾ CITY NĂM 2026 (TÍNH ĐẾN NGÀY 26/05/2026)",
    "link": "https://cih.com.vn/danh-sach-nguoi-thuc-hanh-kham-benh-chua-benh-tai-benh-vien-quoc-te-city-nam-2026-tinh-den-ngay-26-05-2026/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/06/AVATAR_DS_NGUOI-THAM-GIA-KHOA-DTTH.webp",
    "date": "02/06/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Dưới đây là Danh sách người thực hành khám bệnh, chữa bệnh tại Bệnh viện Quốc tế City năm 2026 (tính đến ngày 26/05/2026). Thông tin chi tiế...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 45,
    "title": "CHÚC MỪNG LỄ KÝ KẾT BIÊN BẢN GHI NHỚ HỢP TÁC (MOU) GIỮA BỆNH VIỆN QUỐC TẾ CITY VÀ CÔNG TY TNHH SWAN CLINIC THÀNH CÔNG TỐT ĐẸP",
    "link": "https://cih.com.vn/chuc-mung-le-ky-ket-bien-ban-ghi-nho-hop-tac-mou-giua-benh-vien-quoc-te-city-va-cong-ty-tnhh-swan-clinic-thanh-cong-tot-dep/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/06/7-1024x683.webp",
    "date": "02/06/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Sáng nay ngày 02/06/2026, Bệnh viện Quốc tế City và Công ty TNHH Swan Clinic đã chính thức ký kết Biên bản ghi nhớ hợp tác (MOU), đánh dấu c...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">Tại Lễ ký kết trân trọng đón tiếp sự tham dự của nhiều lãnh đạo cấp cao</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-2\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 46,
    "title": "Đừng lơ là với dấu hiệu nhận biết bệnh sốt xuất huyết",
    "link": "https://cih.com.vn/1325-dung-lo-la-voi-dau-hieu-nhan-biet-benh-sot-xuat-huyet/",
    "img": "https://cih.com.vn/wp-content/uploads/2024/09/dung-lo-la-voi-dau-hieu-nhan-biet-benh-sot-xuat-huyet_66f81c066fb61-jpeg.avif",
    "date": "02/06/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Bước vào mùa mưa, thực trạng người mắc bệnh sốt xuất huyết tăng nhanh, trong đó có không ít trẻ em, các bậc phụ huynh cần chú ý phòng sốt xu...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 47,
    "title": "DẤU ẤN LỚP HỌC TIỀN SẢN QUY MÔ KỶ LỤC TẠI BỆNH VIỆN QUỐC TẾ CITY THU HÚT GẦN 400 MẸ BẦU",
    "link": "https://cih.com.vn/dau-an-lop-hoc-tien-san-quy-mo-ky-luc-tai-benh-vien-quoc-te-city-thu-hut-hon-300-me-bau/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/05/CIH05127-1024x683.webp",
    "date": "30/05/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Ngày 30/05/2026, Bệnh viện Quốc tế City phối hợp Hội Khoa học Sức khỏe TPHCM đã tổ chức thành công Lớp học tiền sản với chủ đề “Dinh dưỡng t...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 48,
    "title": "Hồi phục chức năng tim thận cho bệnh nhân suy tim – suy thận nặng",
    "link": "https://cih.com.vn/hoi-phuc-chuc-nang-tim-than-cho-benh-nhan-suy-tim-suy-than/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/05/Giam-doc-Y-khoa-va-kip-BS-dieu-tri-ca-benh-Huynh-Nhung-70T1.webp",
    "date": "28/05/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Khoa Tim mạch Can thiệp – Bệnh viện Quốc tế City vừa can thiệp thành công, cứu sống nam bệnh nhân 70 tuổi trong tình trạng suy tim nặng, phù...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  },
  {
    "id": 49,
    "title": "HỘI THẢO IVF THÁNG 5: CHẾ ĐỘ DINH DƯỠNG &#038; KIỂM SOÁT CÂN NẶNG TRONG QUÁ TRÌNH ĐIỀU TRỊ IVF",
    "link": "https://cih.com.vn/hoi-thao-ivf-thang-5/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/05/Hoi-thao-IVF-THANG-5-2026-4.webp",
    "date": "25/05/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Hội thảo IVF tại Bệnh viện Quốc tế City mang đến nhiều kiến thức hữu ích về dinh dưỡng, kiểm soát cân nặng trong điều trị IVF, đồng thời tiế...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">Hội thảo IVF – Nơi kiến thức và hy vọng cùng đồng hành</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-2\"><span class=\"ftwp-text\">Dinh dưỡng và cân nặng – “Chìa khóa vàng” trong điều trị IVF</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-3\"><span class=\"ftwp-text\">Câu chuyện IVF thành công chạm đến trái tim nhiều gia đình</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-4\"><span class=\"ftwp-text\">Voucher IVF lên tới 110 triệu đồng – Đồng hành thiết thực cùng các gia đình</span></a></li><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-5\"><span class=\"ftwp-text\">Vì sao nhiều gia đình lựa chọn IVF tại Bệnh viện Quốc tế City?</span></a></li><li class=\"ftwp-item ftwp-has-sub ftwp-collapse\"><button type=\"button\" aria-label=\"Expand or collapse\" class=\"ftwp-icon-collapse\"></button><a class=\"ftwp-anchor\" href=\"#ftoc-heading-6\"><span class=\"ftwp-text\">Lan tỏa hy vọng cho hành trình làm cha mẹ</span></a><ol class=\"ftwp-sub\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-7\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></li></ol></nav>"
  },
  {
    "id": 50,
    "title": "Cắt đại tràng kịp thời cho bệnh nhân ung thư đại tràng sigma có dấu hiệu bán tắc ruột",
    "link": "https://cih.com.vn/cat-dai-trang-kip-thoi-cho-benh-nhan-ung-thu-dai-trang/",
    "img": "https://cih.com.vn/wp-content/uploads/2026/05/5-2.webp",
    "date": "22/05/2026",
    "category": "Khoa Sản &#8211; Nhi",
    "author": "Ban Biên Tập Y Khoa CIH",
    "summary": "Ung thư đại tràng là một trong những bệnh lý tiêu hóa nguy hiểm với xu hướng ngày càng trẻ hóa. Nhiều trường hợp chỉ phát hiện bệnh khi khối...",
    "content": "<div id=\"ftwp-container-outer\" class=\"ftwp-in-post ftwp-float-none\"><div id=\"ftwp-container\" class=\"ftwp-wrap ftwp-hidden-state ftwp-minimize ftwp-middle-right\"><button type=\"button\" id=\"ftwp-trigger\" class=\"ftwp-shape-square ftwp-border-medium\" title=\"click To Maximize The Table Of Contents\"><span class=\"ftwp-trigger-icon ftwp-icon-number\"></span></button><nav id=\"ftwp-contents\" class=\"ftwp-shape-square ftwp-border-medium\" data-colexp=\"collapse\"><header id=\"ftwp-header\"><span id=\"ftwp-header-control\" class=\"ftwp-icon-number\"></span><button type=\"button\" id=\"ftwp-header-minimize\" class=\"ftwp-icon-collapse\" aria-labelledby=\"ftwp-header-title\" aria-label=\"Expand or collapse\"></button><h3 id=\"ftwp-header-title\">Mục lục</h3></header><ol id=\"ftwp-list\" class=\"ftwp-liststyle-decimal ftwp-effect-bounce-to-right ftwp-list-nest ftwp-strong-first ftwp-colexp ftwp-colexp-icon\" style=\"display: none\"><li class=\"ftwp-item\"><a class=\"ftwp-anchor\" href=\"#ftoc-heading-1\"><span class=\"ftwp-text\">BÀI VIẾT LIÊN QUAN</span></a></li></ol></nav>"
  }
];